### ISSUE TITLE
Imported scss file "guides_style_18f" is not in the css folder

### ISSUE THREAD

**Issue by mhokane** [18F/accessibility#65]
I was hoping to contribute to the repo—particularly to fix issue #22 but the relevant imported SCSS file "guides_style_18f" (in "styles.scss") is not included in the CSS folder. Apologies if this is intentional or I'm asking a daft question.

**Comment by mbland** [comment]
It's in the [`guides_style_18` gem](https://rubygems.org/gems/guides_style_18f), from the [18F/guides-style](https://github.com/18F/guides-style) repo. Updates to the style in that gem, when applied to the [Guides Template](https://pages.18f.gov/guides-template/), will also automatically apply to every 18F Page using the gem for its styles.

To develop locally and see the effect of the style changes, [use the `:path` option in the Gemfile](http://bundler.io/gemfile.html) of the Accessibility Guide to point to your local clone of the 18F/guides-style repo.

That said, the style has changed a bit since the image from #22 was taken...I wonder if it's relevant anymore.

**Comment by mhokane** [comment]
Gotcha. Thanks for taking the time to answer. This will be a new adventure for me.
